import os

TWITTER_CONSUMER_KEY = os.environ["TWITTER_CONSUMER_KEY_PRODUCTION"]
TWITTER_CONSUMER_SECRET = os.environ["TWITTER_CONSUMER_SECRET_PRODUCTION"]
TWITTER_ACCESS_TOKEN = os.environ["TWITTER_ACCESS_TOKEN_PRODUCTION"]
TWITTER_ACCESS_TOKEN_SECRET = os.environ["TWITTER_ACCESS_TOKEN_SECRET_PRODUCTION"]

MYAPI_BASIC_AUTH_USER = os.environ["MYAPI_BASIC_AUTH_USER"]
MYAPI_BASIC_AUTH_PASS = os.environ["MYAPI_BASIC_AUTH_PASS"]